# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'o_p_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for o_p_app
	pod 'TagListView', '~> 1.0'
	pod "FlexibleSteppedProgressBar"
	pod 'TextFieldEffects'
	pod 'IQKeyboardManagerSwift'
	pod 'AnimatedTextInput'
	pod 'MessengerKit', :git => 'https://github.com/steve228uk/MessengerKit.git'
	pod 'MessageKit'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'NMapsMap'
    pod 'CenteredCollectionView'
    pod 'InputBarAccessoryView'
end
